# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-09-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_carname_bodytype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carname',
            name='bodytype',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carname',
            name='cardheko',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carname',
            name='cartrade',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='carname',
            name='description',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='carname',
            name='fueltype',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='carname',
            name='imageUrl',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='carname',
            name='youtubeurl',
            field=models.TextField(max_length=50),
        ),
    ]
